#!/bin/bash

mkdir build; cd build

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .. || exit $?

cppcheck --project=compile_commands.json \
    -i thirdparty --quiet --std=c++17 \
    --suppress="*:*/thirdparty/*" \
    --suppress=missingIncludeSystem \
    --suppress=unreadVariable \
    --suppress=unusedFunction \
    --enable=style,performance,portability,information $@
