#!/usr/bin/env bash
set -e

if ! [ -e build ]; then mkdir build; fi; cd build

BUILD_TYPE=Debug
if [ "$1" == "rel" ]; then
   BUILD_TYPE=RelWithDebInfo; shift
fi

cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DTESTS_CATCH2=1 -DTESTS_CLANGTIDY=1 -DTESTS_CPPCHECK=1 "$@"

cmake --build . -j$(nproc)
