#!/usr/bin/env bash
set -e

BUILD_TYPE=Release

if [ "$1" == "inst" ]; then
    INSTALL=1; shift
fi

if ! [ -e build-$BUILD_TYPE ]; then mkdir build-$BUILD_TYPE; fi; 
rm build || true; ln -s build-$BUILD_TYPE build || true

cd build-$BUILD_TYPE

cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DALLOW_WARNINGS=1 "$@"

if [ "`which nproc`" != "" ]; then
   THREADS=`nproc`
elif [ "`sysctl -n hw.ncpu`" != "" ]; then
   THREADS=`sysctl -n hw.ncpu`
fi

if [ "$THREADS" != "" ]; then
   cmake --build . -j$THREADS
else
   cmake --build .
fi

if [ "$INSTALL" ]; then
    sudo cmake --install .
fi
