#!/usr/bin/env bash
set -e

BUILD_TYPE=Debug
if [ "$1" == "rel" ]; then
   BUILD_TYPE=RelWithDebInfo; shift
fi

if ! [ -e build-$BUILD_TYPE ]; then mkdir build-$BUILD_TYPE; fi; 
rm build || true; ln -s build-$BUILD_TYPE build || true

cd build-$BUILD_TYPE

cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
    -DTESTS_CATCH2=1 -DTESTS_CLANGTIDY=1 -DTESTS_CPPCHECK=1 "$@"

cmake --build . -j$(nproc)
