#!/usr/bin/env bash
set -e

BUILD_TYPE=Release

if [ "$1" == "inst" ]; then
    INSTALL=1; shift
fi

if ! [ -e build-$BUILD_TYPE ]; then mkdir build-$BUILD_TYPE; fi; 
rm build || true; ln -s build-$BUILD_TYPE build || true

cd build-$BUILD_TYPE

cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE "$@"

cmake --build . -j$(nproc)

if [ "$INSTALL" ]; then
    sudo cmake --install .
fi
