#!/bin/sh
(find . -iname "*.cpp"; find . -iname "*.hpp"; find . -iname "*.md"; find . -iname "CMakeLists.txt") | 
	grep -v "/build" | grep -v "/thirdparty" | xargs cat > combined.txt

ls -lh combined.txt

