#!/usr/bin/env bash
set -e

(cd src; find . -iname Doxyfile) | while read -r i; do
   echo "doxygen src/$i"
   mkdir -p docs/`dirname $i`
   doxygen -q src/$i
done

if [ "$1" == latex ]; then
   (find . -iname latex) | while read -r d; do
      (cd $d; make)
   done
fi
